### ISSUE TITLE
How do I toggle bluetooth?

### ISSUE THREAD

**Issue by deqing** [vegardinho/alfred_bluetooth_controller#16]
If it's on then off, else turn it on.

Is it possible to do it in one command? Thanks

**Comment by vegardinho** [comment]
It was a feature previously, but I got requested to limit the amount of commands to prevent having to scroll, so I removed it.

**Comment by abondarev84** [comment]
is it possible to have it back as an option to be enabled in the workflow? especially since pair + unpair are much less used (in general/regular usage imo) compared to toggle BT.
thanks in advance

**Comment by vegardinho** [comment]
I guess I could add it in again, all the items might not be visible without scrolling, but personally, I don't mind.

**Comment by abondarev84** [comment]
well pair + unpair take up two slots, maybe it's possible to set pair/unpair into a submenu and to have toggle as a permanent item ? or alternatively have toggle as the permanent item and on/off using a modifier key? just a suggestion

**Comment by vegardinho** [comment]
I agree submenus would probably clean up things. Do you know of any workflows using submenus? Can't seem to find out how to do them.

**Comment by abondarev84** [comment]
this seems like it can work for you since bt case is much simpler compared to what the guy is describing 
[here](https://www.alfredforum.com/topic/17767-creating-nested-navigation-trees-with-list-filters/)

**Comment by vegardinho** [comment]
I've though about this for a little now, and I'm still a little uncertain how to do this best. I'd like to maintain both ease of access (i.e. not too many submenus), visible actions (i.e. actions not too hidden, as with modifiers) and readability (i.e. not too many keywords). Suffice to say, it's not easy to come up with a good solution, and I bet people have different priorities as for those principles, and for the commands they use most frequently. 

A possible setup may look something like the following, which shrimps the main menu to four items, yet preserves all actions, with both visual and quick access to most commands:

- Btd (toggle device connection, modifier for unpairing device)
- Btt (toggle bluetooth status, with modifiers for reset, on, off, show status)
- Btstatus (shows submenu; provides a visible alternative to btt)
    - Reset
    - On
    - Off
    - Toggle
    - Show status
- Btsetup (shows submenu)
    - Pair new device
    - Set favorite device
- Delete btx? Personally I always use the hotkey.

**Comment by abondarev84** [comment]
this looks great!

**Comment by vegardinho** [comment]
After having tried with this setup for a little while, I think I'll keep most of the menus. A lot of the appeal of alfred is that you don't have to remember a lot of hotkeys that aren't visible – if i hide `bton`, `btoff` and `btreset`, I'll have to do trial every time to find the correct modifier most times, because I'll probably have forgot which ones to use. Instead I've opted for hiding some things  (unpair through modifier), and added custom icons for all actions. I think this solves the problem of perceived oversized and chaotic alternatives view:

<img width="719" alt="Captura de pantalla 2022-08-05 a las 6 04 45" src="https://user-images.githubusercontent.com/47058633/182999290-9327aee9-8bc0-4480-b17c-062931da3ca9.png">

**Comment by vegardinho** [comment]
Closed by #27 .

**Comment by abondarev84** [comment]
This really looks good! Thanks for your hard work!
