### ISSUE TITLE
Custom bluetooth names

### ISSUE THREAD

**Issue by a-rock-lobster** [vegardinho/alfred_bluetooth_controller#3]
Firstly, workflow is super. Thanks for sharing. 

I have a suggested (subjective) improvement: I make use of the ability to customise bluetooth device names in system settings and it would be nice if this was reflected in the workflow. For example, when one has a lot of saved devices it would help quickly searching. 

Cheers,

**Comment by vegardinho** [comment]
Thanks! Glad to hear that you enjoy it!

That's a valid suggestion. It seems blueutil doesn't reflect name changes, my guess is that they are only stored locally rather than on-device. 

I would have to look into it, and I probably won't have too much time to do so before long. If you want to have a look at it yourself (or anyone else out there?), I would be happy to implement the changes! Some documentation as to where the custom names are stored/how one can retrieve them would also go a long way to push this upwards on my agenda.

**Comment by a-rock-lobster** [comment]
I would love to help but I have no skills in that department. Just an ideas guy.

Spent a bit of time looking for where the custom names are stored, but no luck yet. All I can say is that custom names are indeed only stored locally.

**Comment by vegardinho** [comment]
I see. Maybe I'll give it a try to see if there is an easy fix. 

Do give me a heads-up if you stumble over something useful.

**Comment by a-rock-lobster** [comment]
A record of bluetooth device custom names are within:
/Library/Preferences/com.apple.Bluetooth.plist

**Comment by vegardinho** [comment]
Now implemented in 37672da3ae175d58503d9742224c5fe7d743b865 / release [v2.0](https://github.com/vegardinho/alfred_bluetooth_controller/releases/tag/2.0)!

I have read somewhere that all names may not be stored in the file you are referencing (and which I use), and that some may reside locally, on-device. Haven't double checked this, but my solution probably isn't entirely bulletproof.

**Comment by a-rock-lobster** [comment]
Cool stuff!
