### ISSUE TITLE
Pairing (btp) broken with macOS Ventura

### ISSUE THREAD

**Issue by kongpuishun** [vegardinho/alfred_bluetooth_controller#33]
Commands like "bton" & "btoff" are working. However, when the command "btd" & "btp" are typed, they automatically turn into fallback options (like the first two pictures).

<img width="611" alt="Screenshot 2023-01-01 at 3 44 26 PM" src="https://user-images.githubusercontent.com/106246957/210164057-ebb7afc7-badb-4d12-9866-fdd094746ebf.png">

<img width="620" alt="Screenshot 2023-01-01 at 3 44 43 PM" src="https://user-images.githubusercontent.com/106246957/210164064-a7d992c7-12c4-4879-90e9-78c4630756ee.png">

<img width="618" alt="Screenshot 2023-01-01 at 3 44 36 PM" src="https://user-images.githubusercontent.com/106246957/210164062-0604eda3-d6ca-4cfe-8801-72137e9c97e8.png">

**Comment by vegardinho** [comment]
~~I’ll need some debug info if you want me to look into it. Also, check out the debugging section in README if you haven’t already. The most likely problem is that blueutil and/or notificator binaries are blocked by macOS and have to be manually permitted to run.~~

~~**Edit:** it seems macOS Ventura has broken `btd` and `btp`. More specifically, [blueutil](https://github.com/toy/blueutil), the binary that handles the bluetooth functionality, seems not to be working properly. I can only hope that it will be updated soon, or else start looking for a permanent alternative.~~

**Edit 2:** It seemed Ventura had not broken `btd`, and that this issue was simply a result of Ventura deleting my paired devices. `btp` seems to be broken on my mac, however.

**Comment by vegardinho** [comment]
As pairing now works on my mac, I'll assume this issue is resolved.
