### ISSUE TITLE
Add configuration settings

### ISSUE THREAD

**Issue by WybeBosch** [vegardinho/alfred_bluetooth_controller#39]
Hey there,

I frequently use your Bluetooth Alfred module and really appreciate all the effort you’ve put into making it,  It’s a fantastic workflow!

However, the confirmation for turning off Bluetooth isn’t something I need. While I can and have edited the Alfred workflow to exclude this confirmation, I find myself needing to redo these changes with each update which has been a bit of a hassle due to the frequent updates you release. (Especially since every command pops up to update the workflow if there is a new version)

Would it be possible to move certain settings, like the confirmation for turning off Bluetooth, to the configuration section? This would ensure that these preferences are retained even after updates.

Thank you for considering this, and keep up the great work!

**Comment by vegardinho** [comment]
Hey!I thought I already had taken care of this, by checking «don’t export settings» when exporting the workflow - but I might have forgotten in some updates, or I’ve misunderdtood how it works. I’ll have a look at how I can fix this in future releases.Thanks for the feedback and for using the workflow!El 24 jun 2024, a las 14:35, Wybe ***@***.***> escribió:﻿
Hey there,
I frequently use your Bluetooth Alfred module and really appreciate all the effort you’ve put into making it open-source. It’s a fantastic tool!
However, the confirmation for turning off Bluetooth isn’t something I need. While I can and have edited the Alfred workflow to exclude this confirmation, I find myself needing to redo these changes with each update which has been a bit of a hassle due to the frequent updates you release.
Would it be possible to move certain settings, like the confirmation for turning off Bluetooth, to the configuration section? This would ensure that these preferences are retained even after updates.
Thank you for considering this, and keep up the great work!

**Comment by WybeBosch** [comment]
As far as i can tell currently the workflow does not have a "configuration" setup
<img width="1223" alt="image" src="https://github.com/vegardinho/alfred_bluetooth_controller/assets/40889930/c1581710-d799-494c-b6c7-3a887f5ca304">

If you were to export certain variables there those do not get modified on updates :)

For example this other workflow has settings there
<img width="1197" alt="image" src="https://github.com/vegardinho/alfred_bluetooth_controller/assets/40889930/23ddace8-d09c-4713-adde-68036728189b">

**Comment by vegardinho** [comment]
Resolved by [v4.1](https://github.com/vegardinho/alfred_bluetooth_controller/releases/tag/4.1).
